# Generated by Django 3.1.3 on 2021-02-20 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
